# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 115ad17a31e2ea50392740925cec1d4857d203f464968f2b86ba880495bb57230baa9b4e655daa1e4ec11437781839a7b0ba7e2cb17173b6165e2351c2632c26

test:
  secret_key_base: 6ef2138623efefd94e1296ed81710fdb6b985603505b927e8cd436c3cc37f7e6e2ad7a834a63927c0ce40404c4d0cc87ae804234c3a3319f1ef6128bfe07f88d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
